name: mobile_driver
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.19.0'


dependencies:
  flutter:
    sdk: flutter

  # annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # api utils
  dio: ^5.4.2+1

  # caching
  shared_preferences: ^2.2.2

  # DI
  get_it: ^7.6.8
  injectable: ^2.4.1

  # functional
  fpdart: ^1.1.0

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  slang: ^3.30.2
  slang_flutter: ^3.30.0

  # icons
  cupertino_icons: ^1.0.6

  # image utils
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # mocking
  http_mock_adapter: ^0.6.1

  # routing
  go_router: ^13.2.2

  # state management
  flutter_bloc: ^8.1.5

  # UI helpers
  flutter_local_notifications: ^17.0.0
  flutter_screenutil: ^5.9.0

  # UI components
  bot_toast: ^4.1.3
  carousel_slider: ^5.0.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  pin_code_fields: ^8.0.1
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0

  # utils
  flow_builder: ^0.1.0
  google_fonts: ^6.2.1
  internet_connection_checker_plus: ^2.3.0
  location: ^6.0.2
  logger: ^2.2.0
  url_launcher: ^6.2.5
  validators: ^3.0.0

  # custom
  mobile_library:
    path: ../mobile-library

dev_dependencies:
  # code analyzers
  very_good_analysis: ^5.1.0

  # generators
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.7
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1

  # testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mockito: ^5.4.4

dependency_overrides:
  intl: ^0.19.0
#  meta: ^1.14.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/about_us/
    - assets/svg/auth/
    - assets/svg/contact_us/
    - assets/svg/home/
    - assets/svg/home/drawer/
    - assets/svg/onboarding/
    - assets/svg/splash/
    - assets/svg/trip_history/
    - assets/image/
    - assets/image/about_us/
    - assets/image/auth/
    - assets/image/home/trip/
    - assets/fonts/
    - assets/fonts/proxima-nova/
    - assets/image/home/
    - assets/image/auth/header_bg.jpeg

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima-nova/ProximaNova-Black.ttf
        - asset: assets/fonts/proxima-nova/ProximaNovaT-Thin.ttf
          weight: 200
        - asset: assets/fonts/proxima-nova/ProximaNova-Light.ttf
          weight: 300
        - asset: assets/fonts/proxima-nova/ProximaNova-Regular.ttf
          weight: 400
        - asset: assets/fonts/proxima-nova/ProximaNova-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/proxima-nova/ProximaNova-Bold.ttf
          weight: 700
        - asset: assets/fonts/proxima-nova/ProximaNova-ExtraBold.ttf
          weight: 900
