///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
// ignore_for_file: dangling_library_doc_comments, implementation_imports
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

class Assets {
  Assets._();

  static const $AssetsAboutUsGen aboutUs = $AssetsAboutUsGen();
  static const $AssetsAuthGen auth = $AssetsAuthGen();
  static const $AssetsCommonGen common = $AssetsCommonGen();
  static const $AssetsContactUsGen contactUs = $AssetsContactUsGen();
  static const $AssetsFontsGen fonts = $AssetsFontsGen();
  static const $AssetsHomeGen home = $AssetsHomeGen();
  static const $AssetsLogoGen logo = $AssetsLogoGen();
  static const $AssetsOnboardingGen onboarding = $AssetsOnboardingGen();
  static const $AssetsRideGen ride = $AssetsRideGen();
  static const $AssetsSplashGen splash = $AssetsSplashGen();
  static const $AssetsTripHistoryGen tripHistory = $AssetsTripHistoryGen();
}

class $AssetsFontsGen {
  const $AssetsFontsGen();

  final $AssetsProximaNovaGen proximaNova = const $AssetsProximaNovaGen();
}

class $AssetsProximaNovaGen {
  const $AssetsProximaNovaGen();

  final String proximaNovaBlack = 'assets/fonts/proxima-nova/ProximaNova-Black.ttf';
  final String proximaNovaBold = 'assets/fonts/proxima-nova/ProximaNova-Bold.ttf';
  final String proximaNovaExtraBold = 'assets/fonts/proxima-nova/ProximaNova-ExtraBold.ttf';
  final String proximaNovaLight = 'assets/fonts/proxima-nova/ProximaNova-Light.ttf';
  final String proximaNovaRegular = 'assets/fonts/proxima-nova/ProximaNova-Regular.ttf';
  final String proximaNovaSemiBold = 'assets/fonts/proxima-nova/ProximaNova-SemiBold.ttf';
  final String proximaNovaTThin = 'assets/fonts/proxima-nova/ProximaNovaT-Thin.ttf';
}

class $AssetsAuthGen {
  const $AssetsAuthGen();

  final AssetGenImage headerBg = const AssetGenImage('assets/auth/header_bg.jpeg');
  final SvgGenImage verification = const SvgGenImage('assets/auth/verification.svg');
  final AssetGenImage verificationBackdrop =
      const AssetGenImage('assets/auth/verification_backdrop.png');
  final AssetGenImage verificationEllipse =
      const AssetGenImage('assets/auth/verification_ellipse.png');
}

class $AssetsHomeGen {
  const $AssetsHomeGen();

  final $AssetsDrawerGen drawer = const $AssetsDrawerGen();
  final $AssetsTripGen trip = const $AssetsTripGen();
  final SvgGenImage dropOff = const SvgGenImage('assets/home/drop_off.svg');
  final SvgGenImage dropOffInverted = const SvgGenImage('assets/home/drop_off_inverted.svg');
  final SvgGenImage droppedDropOff = const SvgGenImage('assets/home/dropped_drop_off.svg');
  final SvgGenImage droppedPickup = const SvgGenImage('assets/home/dropped_pickup.svg');
  final SvgGenImage pickup = const SvgGenImage('assets/home/pickup.svg');
  final SvgGenImage pickupInverted = const SvgGenImage('assets/home/pickup_inverted.svg');
  final SvgGenImage pickupInvertedSmall =
      const SvgGenImage('assets/home/pickup_inverted_small.svg');
}

class $AssetsTripGen {
  const $AssetsTripGen();

  final AssetGenImage payMethodBankili =
      const AssetGenImage('assets/home/trip/pay_method_bankili.png');
  final AssetGenImage payMethodCash = const AssetGenImage('assets/home/trip/pay_method_cash.png');
  final AssetGenImage payMethodSedad = const AssetGenImage('assets/home/trip/pay_method_sedad.png');
  final AssetGenImage standardClassCar =
      const AssetGenImage('assets/home/trip/standard_class_car.png');
  final AssetGenImage standardClassCarCropped =
      const AssetGenImage('assets/home/trip/standard_class_car_cropped.png');
  final AssetGenImage vipClassCar = const AssetGenImage('assets/home/trip/vip_class_car.png');
  final AssetGenImage vipClassCarCropped =
      const AssetGenImage('assets/home/trip/vip_class_car_cropped.png');
}

class $AssetsDrawerGen {
  const $AssetsDrawerGen();

  final SvgGenImage aboutUs = const SvgGenImage('assets/home/drawer/about_us.svg');
  final SvgGenImage aboutUsActive = const SvgGenImage('assets/home/drawer/about_us_active.svg');
  final SvgGenImage contactUs = const SvgGenImage('assets/home/drawer/contact_us.svg');
  final SvgGenImage contactUsActive = const SvgGenImage('assets/home/drawer/contact_us_active.svg');
  final SvgGenImage home = const SvgGenImage('assets/home/drawer/home.svg');
  final SvgGenImage homeActive = const SvgGenImage('assets/home/drawer/home_active.svg');
  final SvgGenImage settings = const SvgGenImage('assets/home/drawer/settings.svg');
  final SvgGenImage settingsActive = const SvgGenImage('assets/home/drawer/settings_active.svg');
  final SvgGenImage tripHistory = const SvgGenImage('assets/home/drawer/trip_history.svg');
  final SvgGenImage tripHistoryActive =
      const SvgGenImage('assets/home/drawer/trip_history_active.svg');
}

class $AssetsLogoGen {
  const $AssetsLogoGen();

  final AssetGenImage logo = const AssetGenImage('assets/logo/logo.png');
}

class $AssetsRideGen {
  const $AssetsRideGen();

  final AssetGenImage driver = const AssetGenImage('assets/ride/driver.png');
  final SvgGenImage mapArrived = const SvgGenImage('assets/ride/map_arrived.svg');
  final SvgGenImage mapMagnifier = const SvgGenImage('assets/ride/map_magnifier.svg');
  final SvgGenImage pencil = const SvgGenImage('assets/ride/pencil.svg');
  final SvgGenImage tripDropOffLocation =
      const SvgGenImage('assets/ride/trip_drop_off_location.svg');
  final SvgGenImage tripPickupLocation = const SvgGenImage('assets/ride/trip_pickup_location.svg');
}

class $AssetsCommonGen {
  const $AssetsCommonGen();

  final SvgGenImage arrow = const SvgGenImage('assets/common/arrow.svg');
  final SvgGenImage callIcon = const SvgGenImage('assets/common/call_icon.svg');
  final SvgGenImage messageIcon = const SvgGenImage('assets/common/message_icon.svg');
}

class $AssetsSplashGen {
  const $AssetsSplashGen();

  final SvgGenImage map = const SvgGenImage('assets/splash/map.svg');
}

class $AssetsAboutUsGen {
  const $AssetsAboutUsGen();

  final SvgGenImage centerSeparator = const SvgGenImage('assets/about_us/center_separator.svg');
  final SvgGenImage circleArrowAntiClockwise =
      const SvgGenImage('assets/about_us/circle_arrow_anti_clockwise.svg');
  final SvgGenImage circleArrowClockwise =
      const SvgGenImage('assets/about_us/circle_arrow_clockwise.svg');
  final AssetGenImage headerBg = const AssetGenImage('assets/about_us/header_bg.jpeg');
  final SvgGenImage leftSeparator = const SvgGenImage('assets/about_us/left_separator.svg');
  final SvgGenImage ourMissionBgVector =
      const SvgGenImage('assets/about_us/our_mission_bg_vector.svg');
  final SvgGenImage serveBookingIcon = const SvgGenImage('assets/about_us/serve_booking_icon.svg');
  final SvgGenImage serveDriversIcon = const SvgGenImage('assets/about_us/serve_drivers_icon.svg');
  final SvgGenImage servePaymentIcon = const SvgGenImage('assets/about_us/serve_payment_icon.svg');
  final SvgGenImage serveTrackingIcon =
      const SvgGenImage('assets/about_us/serve_tracking_icon.svg');
}

class $AssetsContactUsGen {
  const $AssetsContactUsGen();

  final SvgGenImage calling = const SvgGenImage('assets/contact_us/calling.svg');
  final SvgGenImage mail = const SvgGenImage('assets/contact_us/mail.svg');
}

class $AssetsOnboardingGen {
  const $AssetsOnboardingGen();

  final SvgGenImage bottomIllustration =
      const SvgGenImage('assets/onboarding/bottom_illustration.svg');
  final SvgGenImage feelCozyIcon = const SvgGenImage('assets/onboarding/feel_cozy_icon.svg');
  final SvgGenImage findNearbyIcon = const SvgGenImage('assets/onboarding/find_nearby_icon.svg');
  final SvgGenImage smoothQuickIcon = const SvgGenImage('assets/onboarding/smooth_quick_icon.svg');
  final SvgGenImage topIllustration = const SvgGenImage('assets/onboarding/top_illustration.svg');
}

class $AssetsTripHistoryGen {
  const $AssetsTripHistoryGen();

  final SvgGenImage dropOff = const SvgGenImage('assets/trip_history/drop_off.svg');
  final SvgGenImage pickUp = const SvgGenImage('assets/trip_history/pick_up.svg');
}

class AssetGenImage {
  const AssetGenImage(this._assetName, {this.size, this.flavors = const {}});

  final String _assetName;

  final Size? size;
  final Set<String> flavors;

  Image image({
    Key? key,
    AssetBundle? bundle,
    ImageFrameBuilder? frameBuilder,
    ImageErrorWidgetBuilder? errorBuilder,
    String? semanticLabel,
    bool excludeFromSemantics = false,
    double? scale,
    double? width,
    double? height,
    Color? color,
    Animation<double>? opacity,
    BlendMode? colorBlendMode,
    BoxFit? fit,
    AlignmentGeometry alignment = Alignment.center,
    ImageRepeat repeat = ImageRepeat.noRepeat,
    Rect? centerSlice,
    bool matchTextDirection = false,
    bool gaplessPlayback = false,
    bool isAntiAlias = false,
    String? package,
    FilterQuality filterQuality = FilterQuality.low,
    int? cacheWidth,
    int? cacheHeight,
  }) {
    return Image.asset(
      _assetName,
      key: key,
      bundle: bundle,
      frameBuilder: frameBuilder,
      errorBuilder: errorBuilder,
      semanticLabel: semanticLabel,
      excludeFromSemantics: excludeFromSemantics,
      scale: scale,
      width: width,
      height: height,
      color: color,
      opacity: opacity,
      colorBlendMode: colorBlendMode,
      fit: fit,
      alignment: alignment,
      repeat: repeat,
      centerSlice: centerSlice,
      matchTextDirection: matchTextDirection,
      gaplessPlayback: gaplessPlayback,
      isAntiAlias: isAntiAlias,
      package: package,
      filterQuality: filterQuality,
      cacheWidth: cacheWidth,
      cacheHeight: cacheHeight,
    );
  }

  ImageProvider provider({
    AssetBundle? bundle,
    String? package,
  }) {
    return AssetImage(
      _assetName,
      bundle: bundle,
      package: package,
    );
  }

  Widget custom({
    Key? key,
    required Widget Function(BuildContext context, String assetPath) builder,
  }) {
    return Builder(
      key: key,
      builder: (context) => builder(context, _assetName),
    );
  }

  String get path => _assetName;

  String get keyName => _assetName;
}

class SvgGenImage {
  const SvgGenImage(this._assetName);

  final String _assetName;

  SvgPicture svg({
    Key? key,
    bool matchTextDirection = false,
    AssetBundle? bundle,
    String? package,
    double? width,
    double? height,
    BoxFit fit = BoxFit.contain,
    AlignmentGeometry alignment = Alignment.center,
    bool allowDrawingOutsideViewBox = false,
    WidgetBuilder? placeholderBuilder,
    String? semanticsLabel,
    bool excludeFromSemantics = false,
    SvgTheme? theme,
    Clip clipBehavior = Clip.hardEdge,
  }) {
    return SvgPicture.asset(
      _assetName,
      key: key,
      matchTextDirection: matchTextDirection,
      bundle: bundle,
      package: package,
      width: width,
      height: height,
      fit: fit,
      alignment: alignment,
      allowDrawingOutsideViewBox: allowDrawingOutsideViewBox,
      placeholderBuilder: placeholderBuilder,
      semanticsLabel: semanticsLabel,
      excludeFromSemantics: excludeFromSemantics,
      theme: theme,
      clipBehavior: clipBehavior,
    );
  }

  Widget custom({
    Key? key,
    required Widget Function(BuildContext context, String assetPath) builder,
  }) {
    return Builder(
      key: key,
      builder: (context) => builder(context, _assetName),
    );
  }

  String get path => _assetName;

  String get keyName => _assetName;
}
