///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String aboutUsCenterSeparator = 'assets/svg/about_us/center_separator.svg';
  static const String aboutUsCircleArrowAntiClockwise =
      'assets/svg/about_us/circle_arrow_anti_clockwise.svg';
  static const String aboutUsCircleArrowClockwise =
      'assets/svg/about_us/circle_arrow_clockwise.svg';
  static const String aboutUsHeaderBg = 'assets/image/about_us/header_bg.jpeg';
  static const String aboutUsLeftSeparator = 'assets/svg/about_us/left_separator.svg';
  static const String aboutUsOurMissionBgVector = 'assets/svg/about_us/our_mission_bg_vector.svg';
  static const String aboutUsServeBookingIcon = 'assets/svg/about_us/serve_booking_icon.svg';
  static const String aboutUsServeDriversIcon = 'assets/svg/about_us/serve_drivers_icon.svg';
  static const String aboutUsServePaymentIcon = 'assets/svg/about_us/serve_payment_icon.svg';
  static const String aboutUsServeTrackingIcon = 'assets/svg/about_us/serve_tracking_icon.svg';
  static const String authHeaderBg = 'assets/image/auth/header_bg.jpeg';
  static const String authVerification = 'assets/svg/auth/verification.svg';
  static const String authVerificationBackdrop = 'assets/image/auth/verification_backdrop.png';
  static const String authVerificationEllipse = 'assets/image/auth/verification_ellipse.png';
  static const String contactUsCalling = 'assets/svg/contact_us/calling.svg';
  static const String contactUsMail = 'assets/svg/contact_us/mail.svg';
  static const String drawerAboutUs = 'assets/svg/home/drawer/about_us.svg';
  static const String drawerAboutUsActive = 'assets/svg/home/drawer/about_us_active.svg';
  static const String drawerContactUs = 'assets/svg/home/drawer/contact_us.svg';
  static const String drawerContactUsActive = 'assets/svg/home/drawer/contact_us_active.svg';
  static const String drawerHome = 'assets/svg/home/drawer/home.svg';
  static const String drawerHomeActive = 'assets/svg/home/drawer/home_active.svg';
  static const String drawerSettings = 'assets/svg/home/drawer/settings.svg';
  static const String drawerSettingsActive = 'assets/svg/home/drawer/settings_active.svg';
  static const String drawerTripHistory = 'assets/svg/home/drawer/trip_history.svg';
  static const String drawerTripHistoryActive = 'assets/svg/home/drawer/trip_history_active.svg';
  static const String homeDropOff = 'assets/svg/home/drop_off.svg';
  static const String homeDropOffInverted = 'assets/svg/home/drop_off_inverted.svg';
  static const String homeDroppedDropOff = 'assets/svg/home/dropped_drop_off.svg';
  static const String homeDroppedPickup = 'assets/svg/home/dropped_pickup.svg';
  static const String homePickup = 'assets/svg/home/pickup.svg';
  static const String homePickupInverted = 'assets/svg/home/pickup_inverted.svg';
  static const String homePickupInvertedSmall = 'assets/svg/home/pickup_inverted_small.svg';
  static const String imageAuthHeaderBg = 'assets/image/auth/header_bg.jpeg';
  static const String imageLogo = 'assets/image/logo.png';
  static const String onboardingBottomIllustration =
      'assets/svg/onboarding/bottom_illustration.svg';
  static const String onboardingFeelCozyIcon = 'assets/svg/onboarding/feel_cozy_icon.svg';
  static const String onboardingFindNearbyIcon = 'assets/svg/onboarding/find_nearby_icon.svg';
  static const String onboardingSmoothQuickIcon = 'assets/svg/onboarding/smooth_quick_icon.svg';
  static const String onboardingTopIllustration = 'assets/svg/onboarding/top_illustration.svg';
  static const String proximaNovaProximaNovaBlack =
      'assets/fonts/proxima-nova/ProximaNova-Black.ttf';
  static const String proximaNovaProximaNovaBold = 'assets/fonts/proxima-nova/ProximaNova-Bold.ttf';
  static const String proximaNovaProximaNovaExtraBold =
      'assets/fonts/proxima-nova/ProximaNova-ExtraBold.ttf';
  static const String proximaNovaProximaNovaLight =
      'assets/fonts/proxima-nova/ProximaNova-Light.ttf';
  static const String proximaNovaProximaNovaRegular =
      'assets/fonts/proxima-nova/ProximaNova-Regular.ttf';
  static const String proximaNovaProximaNovaSemiBold =
      'assets/fonts/proxima-nova/ProximaNova-SemiBold.ttf';
  static const String proximaNovaProximaNovaTThin =
      'assets/fonts/proxima-nova/ProximaNovaT-Thin.ttf';
  static const String splashMap = 'assets/svg/splash/map.svg';
  static const String tripHistoryDropOff = 'assets/svg/trip_history/drop_off.svg';
  static const String tripHistoryPickUp = 'assets/svg/trip_history/pick_up.svg';
  static const String tripPayMethodCash = 'assets/image/home/trip/pay_method_cash.png';
  static const String tripStandardClassCar = 'assets/image/home/trip/standard_class_car.png';
  static const String tripStandardClassCarCropped =
      'assets/image/home/trip/standard_class_car_cropped.png';
  static const String tripVipClassCar = 'assets/image/home/trip/vip_class_car.png';
  static const String tripVipClassCarCropped = 'assets/image/home/trip/vip_class_car_cropped.png';
}
